-- ============================================================================
-- Migration: Protect rent_payments generated by claims
-- ============================================================================

CREATE OR REPLACE FUNCTION public.protect_claim_rent_payments()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Prevent DELETE
  IF TG_OP = 'DELETE' THEN
    IF OLD.note LIKE '%Verrechnung über Forderungsakte%' THEN
      RAISE EXCEPTION 'Diese Zahlung ist an eine Forderungsakte geknüpft. Bitte löschen Sie die Zahlung direkt in der Timeline der jeweiligen Forderung.';
    END IF;
    RETURN OLD;
  END IF;
  
  -- Prevent UPDATE of amounts
  IF TG_OP = 'UPDATE' THEN
    IF OLD.note LIKE '%Verrechnung über Forderungsakte%' AND OLD.amount != NEW.amount THEN
      RAISE EXCEPTION 'Der Betrag einer forderungsgebundenen Zahlung kann nicht manuell in der Buchhaltung geändert werden. Bitte stornieren Sie die Zahlung in der zugehörigen Forderungsakte.';
    END IF;
    RETURN NEW;
  END IF;

  RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS block_claim_rent_payments_modification ON rent_payments;

CREATE TRIGGER block_claim_rent_payments_modification
BEFORE DELETE OR UPDATE ON rent_payments
FOR EACH ROW
EXECUTE PROCEDURE protect_claim_rent_payments();
